# Generated by Django 4.1.4 on 2023-05-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_category_name_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('ACTIVATED', 'ACTIVATED'), ('NOT_ACTIVATED', 'NOT_ACTIVATED'), ('DONE', 'DONE')], default='NEW', max_length=50),
        ),
    ]
