apiVersion: v1
kind: Service
metadata:
  name: alok-test-docker-django-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: alok-test-docker-django-deployment