name: Django CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
    build:
      runs-on: ubuntu-latest
      env:
        CLUSTER_NAME: poc-django
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Insall doctl
          uses: digitalocean/action-doctl@v2
          with:
            token: ${{ secrets.DO_API_TOKEN_KEY }}
        - name: Login to DO Container Registry with short-lived creds
          run: doctl registry login --expiry-seconds 1200
        - name: Build container image
          working-directory: .
          run: |
            docker build -f Dockerfile \
              -t registry.digitalocean.com/alok-django-kops/django-k8s-api:latest \
              -t registry.digitalocean.com/alok-django-kops/django-k8s-api:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} \
              .
        - name: Push image
          run: |
            docker push registry.digitalocean.com/alok-django-kops/django-k8s-api --all-tags
        - name: K8s cluster kubeconfig file with/ short-lived creds
          run: |
            doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}
        - name: trigger rollout for deployment
          run: |
            kubectl rollout restart deployment.apps/alok-test-docker-django-deployment
        - name: Wait for rollout to finish
          run: |
            kubectl rollout status deployment.apps/alok-test-docker-django-deployment